---
title: ""
output: 
  html_document:
    theme: flatly
    highlight: tango
---

<link rel="stylesheet" href="style.css" type="text/css">

<style>
body {
text-align: justify}
</style>

## **On-going Research Projects**
<hr style="border:1px solid black"> <!-- add black line -->


#### 1). Water demand and the value of water in the US Southeast, with [Dr. Tatiana Borisova](https://www.ers.usda.gov/authors/ers-staff-directory/tatiana-borisova), USDA-ERS


#### 2). Economics of managed aquifer recharge in the Mississippi Embayment: An integration of MODFLOW with an economic model, with [Dr. Kent Kovacs ](https://ualr.edu/cbhhs/faculty/dr-kent-kovacs/), University of Arkansas at Little Rock, [Dr. Helen E. Dahlke](https://dahlke.ucdavis.edu/about/), UC Davis, [Dr. Ahmed Ali](https://orcid.org/0000-0002-8991-5180), Irrigation and Hydraulics Department, Faculty of Engineering, Cairo University, Giza, Egypt and former postdoc at UC Davis, and [Dr. Steve Wallander](https://www.ers.usda.gov/authors/ers-staff-directory/steven-wallander), USDA-ERS


#### 3). The economic impacts of salinity intrusion on coastal rice production: a comprehensive micro-macro analysis, with [Dr. Alvaro Durand-Morat](https://agribusiness.uark.edu/directory/index/uid/adurand/name/Alvaro+Durand-Morat/), University of Arkansas at Fayetteville, [Dr. Hyunwoo Kang](https://scholar.google.com/citations?user=D43NLY8AAAAJ&hl=en), Oregon State University, [Dr. Bradford Mills](https://aaec.vt.edu/people/faculty/mills-bradford.html) and [Dr. Venkataramana Sridhar](https://www.bse.vt.edu/people/faculty/venkat-sridhar.html), Virginia Tech, and [Dr. Kieu Le](https://fieldtomarket.org/the-alliance/our-staff/), Field to Market


#### 4). Regional supply elasticities using remote-sensing data and implications of Sustainable Groundwater Management Act (SGMA) on agricultural production in California, with [Dr. Bruce Babcock](https://profiles.ucr.edu/app/home/profile/babcockb) and [Dr. Mehdi Nemati](https://profiles.ucr.edu/app/home/profile/mehdin), University of California, Riverside


#### 5). An integrated tillage choice dynamics and biophysical modeling framework - impacts of periodic tillage on water quality in Upper Mississippi River Basin, with [Dr. Lyubov A. Kurkalova](https://www.ncat.edu/employee-bio.php?directoryID=1629715345), North Carolina A&T State, [Dr. Jaehak Jeong](https://blackland.tamu.edu/people/research/scientists/jeong-jaehak/), Texas A&M, and [Dr. Philip W. Gassman](https://www.card.iastate.edu/people/philip-gassman), Iowa State University


#### 6). Modeling field level tillage dynamics with cropland data layer (CDL): an application of Entropy approach to evaluate the effect of shifting production toward corn monoculture on farmer’s tillage choices in Iowa, with [Dr. Lyubov A. Kurkalova](https://www.ncat.edu/employee-bio.php?directoryID=1629715345), North Carolina A&T State, and [Dr. Silvia Secchi](https://geography.uiowa.edu/people/silvia-secchi), University of Iowa


#### 7). Evaluating the economic potential for soil organic carbon sequestration: an integrated modeling approach, with [Dr. Kieu Le](https://fieldtomarket.org/the-alliance/our-staff/), Field to Market, [Dr. Olaf David](https://www.engr.colostate.edu/ce/people/olaf-david/), Colorado State University, Fort Collins, [Dr. Natalja Čerkasova](https://blackland.tamu.edu/people/research/scientists/cerkasova-natalja/), and [Dr. Jeff Arnold](https://www.ars.usda.gov/plains-area/temple-tx/grassland-soil-and-water-research-laboratory/people/jeffrey-arnold/), Texas A&M AgriLife Research, [Mr. Frank Geter](https://www.ars.usda.gov/southeast-area/oxford-ms/national-sedimentation-laboratory/water-quality-and-ecology-research/news/awardsrecognition/visitors/), USDA-NRCS, and [Mr. Jack Carlson](https://www.engr.colostate.edu/ce/people/jack-carlson/), Colorado State University, Fort Collins.          

