---
title: ""
output:
  html_document:
    theme: flatly
    highlight: tango
    
# output:
#   cleanrmd::html_document_clean:
#   theme: markdown-air
---

#
#
<!-- <link rel="stylesheet" href="style.css" type="text/css"> -->


<style>
body {
text-align: justify}
</style>



## **Published/Accepted Papers**
<hr style="border:1px solid black"> <!-- add black line -->
#### 25). **Tran, D.Q.** & Kurkalova, L.A. Estimation of the continuity of tillage choices with aggregate and incomplete data: An application of Entropy approach. *Journal of the Agricultural and Applied Economics Association (JAAEA)*. **Accepted**.

#### 24). **Tran, D.Q.** & Le, N. K. 2025. [Sea-level rise and saltwater intrusion: economic estimates of impacts of nature-based mitigation policies under uncertainty](https://www.mdpi.com/2073-4441/17/9/1355). Water. 17 (1355), 1-38.

#### 23). **Tran, D.Q**., Le, N. K., Durand-Morat, A., Nguyen, N.T. N., Bairagi, S., Huynh, V.T. M & Tran, V. T. 2025. [Is it worth It? land-fallowing and saltwater intrusion control under uncertainty](https://doi.org/10.1016/j.scitotenv.2025.178711). *Science of the Total Environment*. 966 (2025), 1-15.

#### 22). **Tran, D. Q**. 2024. [Annual assessment of Florida’s water resources: supply and demand. In: 2024 Annual assessment of Florida's water resources and conservation lands](http://edr.state.fl.us/Content/natural-resources/2024_AnnualAssessmentWaterResources_Chapter3.pdf). *Office of Economic and Demographic Research, Florida Legislature*.  

#### 21). Pathak, S., Wang H., **Tran, D. Q** & Adusumilli, N., C. 2023. [Persistence and disadoption of sustainable agricultural practices in the Mississippi Delta region](https://doi.org/10.1002/agj2.21519). *Agronomy Journal*. 116(2), 765-776.  

#### 20). **Tran, D. Q** & Kurkalova, L.A. 2023. [Testing for complementary between the use of continuous no-till and cover crops: an application of Entropy and Bayesian approaches](https://doi.org/10.1016/j.soisec.2023.100118). *Soil Security*. 13, 100118.

#### 19). **Tran, D.Q.**, Nguyen, N.T. N., Huynh, V.T. M., Bairagi, S., Le, N. K., Tran, V. T & Durand-Morat, A. 2023. [Modeling Saltwater Intrusion Risk in the Presence of Uncertainty](https://doi.org/10.1016/j.scitotenv.2023.168140). *Science of the Total Environment*. 908, 168140. [Preprint version can be accessed here](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4510877). 

#### 18). Ali, A.M. A., **Tran, D.Q.**, Kovacs, K & Dahlke, H. 2023. [Hydro-economic modeling of managed aquifer recharge in the lower Mississippi](https://onlinelibrary.wiley.com/doi/10.1111/1752-1688.13141?af=R). *Journal of the American Water Resources Association*. 00 (0): 1– 22 

#### 17). Nemati, M., **Tran, D.Q** & Schwabe, K. 2023. [Residential Water Conservation and the Rebound Effects: A Temporal Decomposition and Investigation](https://doi.org/10.1029/2022WR032169). *Water Resources Research*, 59 (4), 1-18.  

#### 16). **Tran, D. Q.**, Borisova, T & Beggs, K. 2023. [The Cost of Alternative Water Supply and Efficiency Options under Uncertainty: An Application of Modern Portfolio Theory and Chebyshev’s Inequality](https://doi.org/10.3390/earth4010003). *Earth*, 2023, 4(1), 40-65.

#### 15). **Tran, D. Q.** 2023. [Annual assessment of Florida’s water resources: supply and demand. In: 2023 Annual assessment of Florida's water resources and conservation lands](http://edr.state.fl.us/Content/natural-resources/2023_AnnualAssessmentWaterResources_Chapter3.pdf). *Office of Economic and Demographic Research, Florida Legislature*.

#### 14). **Tran, D. Q.**, Beggs, K., Cosgray, C & MacPherson, D. 2022. Volume 2: [Annual Assessment of Florida's Water Resources: Supply, Demand, and Quality](http://edr.state.fl.us/Content/natural-resources/LandandWaterAnnualAssessment_2022Edition_Volume2.pdf). *Office of Economic and Demographic Research, Florida Legislature*.

#### 13). Nemati, M & **Tran, D. Q.** 2022. [The impact of COVID-19 on urban water consumption in the United States](https://doi.org/10.3390/w14193096). *Water*. 14(19), 3096.

#### 12). Bairagi, S.K., Mishra, A. K & **Tran, D. Q.** 2021. [Disentangling gender-differentiated impact on food security and poverty: empirical evidence from Vietnam](https://doi.org/10.1002/jid.3611). *Journal of International Development*, 34(3), 493– 511.

#### 11). Babcock, B., Nemati, M., & **Tran, D. Q.** (2021). [Will citrus survive SGMA? Understanding California grower crop choice](https://www.researchgate.net/publication/371867520_Will_citrus_survive_SGMA_Understanding_California_grower_crop_choice#fullTextFileContent). *Citrograph*, 12(4).32–37.

#### 10). **Tran, D.Q.** & Kovacs, K. 2021. [Climate uncertainty and optimal groundwater augmentation](https://doi.org/10.1029/2021WR030114). *Water Resources Research*, 57 (9), 1-19.

#### 9). **Tran, D.Q.**, Kovacs, K & West, G. 2020. [Spatial economic predictions of managed aquifer recharge for an agricultural landscape](https://doi.org/10.1016/j.agwat.2020.106337). *Agricultural Water Management*, 66 (4), 666-682.

#### 8). **Tran, D.Q.**, Kovacs, K & Wallander, S. 2020. [Water conservation with managed aquifer recharge under increased drought risk](https://link.springer.com/article/10.1007/s00267-020-01329-x). *Environmental Management*, 241, 1-11.

#### 7). **Tran, D.Q.**, Kovacs, K & Wallander, S. 2019. [Long-run optimization of landscape-level irrigation through managed aquifer recharge or expanded surface reservoirs](https://doi.org/10.1016/j.jhydrol.2019.124220). *Journal of Hydrology*, 579 (2019), 1-12.

#### 6). **Tran, D.Q.** & Kurkalova, L.A. 2019. [Persistence in tillage decisions: aggregate data analysis](https://doi.org/10.1016/j.iswcr.2019.03.002). *International Soil and Water Conservation Research*, 7 (2), 109-118.

#### 5). Huynh, V. T. M., Avtar, M. R., Kumar, P., **Tran, D.Q.**, Tran, T. V., Behra, H. C & Masaaki, K. 2019. [Groundwater Quality Assessment using Fuzzy-AHP in An Giang province of Vietnam](https://doi.org/10.3390/geosciences9080330). *Geosciences*, 9 (330), 1-23.

#### 4). Huynh, V. T. M., Masaaki, K., Tran, T. V., **Tran, D.Q.**, Le, K. N., Avtar, M. R & Osaki, M. 2019. [Effects of Multi-Dike Protection Systems on Surface Water Quality in the Vietnamese Mekong Delta](https://doi.org/10.3390/w11051010). *Water*, 11 (1010), 1-23.

#### 3). Kurkalova, L.A & **Tran, D.Q.**[“Impact of stover collection on Iowa land use.”](https://link.springer.com/chapter/10.1007/978-3-319-74536-7_8) In: Li, R, and Monti, A (Eds.), Land Allocation for Biomass: Challenges and Opportunities, 2018.

#### 2). Le, K. N ., Manoj K. J., Jeong, J., Gassman, P, W., Reyes, M, R., Doro, L., **Tran, D.Q.** & Hok, L. 2018. [Evaluation of long-term SOC and crop productivity within conservation systems using GFDL CM2.1 and EPIC](https://doi.org/10.3390/su10082665). *Sustainability*, 10 (2665), 1-18. 

#### 1). Kurkalova, L.A. & **Tran, D.Q.** 2017. [Is the use of no-till continuous or rotational? Quantifying tillage dynamics from time-ordered spatially aggregated data](https://www.tandfonline.com/doi/abs/10.2489/jswc.72.2.131). *Journal of Soil and Water Conservation*, 72(2), 131-138.


### **Papers Under Review and Preparation**
<hr style="border:1px solid black"> <!-- add black line -->

#### 8). **Tran, D.Q.** & Kurkalova, L.A. Cost of continuous conservation tillage: an application of Network Flow. **Under review**.

#### 7). **Tran, D.Q** & Le, N. K. Groundwater depletion and economic value of managed aquifer recharge in the Mississippi River Valley alluvial aquifer. **Under review**.

#### 6). Babcock, B., Nemati, M & **Tran, D. Q**. Estimation of supply elasticities for non-exchange traded commodities. **Under review**. [Preprint version available here](https://spp.ucr.edu/document/estimation-supply-elasticities-non-exchange-traded-commodities-full-paper).

#### 5). **Tran, D. Q.** & Borisova, T. Quantifying effects of climate extremes and socioeconomic dynamics on future water demand and water supply investment: a hybrid machine learning approach. *In preparation*.

#### 4). **Tran, D.Q.**, Le, N. K., Durand-Morat, A., Nguyen, N.T. N., Bairagi, S., Huynh, V.T. M & Tran, V. T.  Simulating the impact of water demand management options on saltwater intrusion in a mega-delta under uncertainty. *In preparation*.

#### 3). Nemati, M., **Tran, D.Q** & Schwabe, K. Effect of water-reduction mandate during drought on hourly residential water use. *In preparation*.

#### 2). **Tran, D.Q** & Le, N. K. Does corn move north? An assessment of recent changes in crop rotation in the U.S. Corn Belt using remote sensing data. *In preparation*.

#### 1). **Tran, D.Q.**, Nguyen, N.T. N., Bairagi, S., Le, N. K., Huynh, V.T. M. A regional hydro-economic model for estimating the costs of increased saltwater intrusion risk on agriculture. *In preparation*.

### **Conferences: please see my [CV](https://dattran-hydroeco.github.io/my_CV_updatedJune2023.html)**