---
title: ""
output: 
  html_document:
    theme: flatly
    highlight: tango
---

#
#
<link rel="stylesheet" href="style.css" type="text/css">


<!-- <style> -->
<!-- body { -->
<!-- text-align: justify} -->
<!-- </style> -->


## **Announcements**
<hr style="border:1px solid black"> <!-- add black line -->
#### I am a Guest Editor of the Special Issue: Sustainable Water Management in Agricultural Irrigation. Journal: Water. [More information about the Special Issue can be found here](https://www.mdpi.com/journal/water/special_issues/JD60IDD43H) or contact me tran.dat@leg.state.fl.us


## **Media coverage**
<hr style="border:1px solid black"> <!-- add black line -->

#### Climate, Featured, Food, Global of the Columbia Journalism School ([Climate Adaptation Comes at a Cost for Vietnam’s Rice Basket](https://columbianewsservice.com/2025/04/10/climate-adaptation-comes-at-a-cost-for-vietnams-rice-basket/?fbclid=IwY2xjawJkwPNleHRuA2FlbQIxMQABHjqq20pFlY4792lz8aOZD7Goj-WNNiuZ6KeRzGm1NoThgRllDuIkgROxkP1C_aem_VlWeEqsY5XEaziTkFsf2cg))

#### UCR News, PHYS.ORG, and THE HILL ([Forced water-use cuts made California more water-wise](https://thehill.com/policy/equilibrium-sustainability/3971061-forced-conservation-measures-made-californians-more-water-wise-study/))


#### The Invading Sea ([Could Florida experience a significant water supply shortage by 2025?](https://www.theinvadingsea.com/2024/09/10/florida-water-supply-shortage-2025-infrastructure-legislature-seminole-compact-taxwatch/))

<!-- #### Florida TaxWatch ([Florida’s Water Supply: Could Florida Experience a Significant Water Supply Shortage by 2025?](https://floridataxwatch.org/Research/Full-Library/florida-water-supply-shortage-2025)) -->

## **Recent talks**
<hr style="border:1px solid black"> <!-- add black line -->

### **2024 AAEA conferences**

#### 1). **Tran, D. Q** & Borisova, T. [Forecasting Expenditures to Meet Regional Water Demand](https://ageconsearch.umn.edu/record/343688/files/28291.pdf). Selected paper, Agricultural & Applied Economics Association Annual Meeting, New Orleans, LA, 07/2024. [Click here for more information](https://ageconsearch.umn.edu/record/343688/files/28291.pdf)

#### 2). **Tran, D.Q.**, Le, N. K., Durand-Morat, A., Nguyen, N.T. N., Bairagi, S., Huynh, V.T. M & Tran, V, T. [How Many Acres Do We Need to Fallow to Control Saltwater Intrusion in a Mega-Delta under Uncertainty?](https://ageconsearch.umn.edu/record/343689/files/28293.pdf). Selected paper, Agricultural & Applied Economics Association Annual Meeting, New Orleans, LA, 07/2024. [Click here for more information](https://ageconsearch.umn.edu/record/343689/files/28293.pdf)
